### ISSUE TITLE
how to call package in python

### ISSUE THREAD

**Issue by jakubMitura14** [cjdoris/pyjuliapkg#6]
Hello i added juliapkg.json
```
{
    "packages": {
        "MedPipe3D": {
            "uuid": "80492ae4-ba08-4770-a16e-2cec06b8739e",
            "version": "0.1.0"
        }
    }
}
```
I had written in python 
```
from juliacall import Main as jl
import juliapkg
juliapkg.resolve()
```

no errors here

still in python
```
import MedPipe3D
```
do not work

but how to start using MedPipe3D now - I had no problem in calling python packages in Julia using your tool - really fantastic job, here it is probably sth simple also - but I just do not see how to import MedPipe3D as a reference

**Comment by cjdoris** [comment]
This is what you want:
```python
from juliacall import Main as jl
jl.seval("using MedPipe3D")
jl.MedPipe3D  # this is the MedPipe3D module
```
